# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=254)),
                ('price', models.FloatField(default=0.0)),
                ('score', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('release_datetime', models.DateTimeField(verbose_name='release date')),
                ('large_image', models.ImageField(upload_to='uploads/large/')),
                ('small_image', models.ImageField(upload_to='uploads/small/')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('screen_name', models.CharField(max_length=30)),
                ('avatar', models.ImageField(upload_to='uploads/avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fume.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_datetime', models.DateTimeField(verbose_name='date of reward')),
                ('expiry_datetime', models.DateTimeField(verbose_name='expiry date')),
                ('is_used', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fume.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=254)),
                ('count', models.IntegerField(default=0)),
                ('tag_type', models.CharField(max_length=30)),
                ('games', models.ManyToManyField(to='fume.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='date of transaction')),
                ('subtotal', models.FloatField(default=0.0)),
                ('num_of_rewards_used', models.IntegerField(default=0)),
                ('actual_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(max_length=254)),
                ('games', models.ManyToManyField(to='fume.Game')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fume.Member')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fume.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fume.Publisher'),
        ),
    ]
