# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(to='fume.Game')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fume.Member')),
            ],
        ),
    ]
