# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fume.models


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0002_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='games',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='member',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='actual_amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='num_of_rewards_used',
            new_name='rewards_used',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_datetime',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='expiry_datetime',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='reward_datetime',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='game',
            name='description_long',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description_short',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Release Date'),
        ),
        migrations.AddField(
            model_name='member',
            name='acc_spending',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='member',
            name='recommended',
            field=models.ManyToManyField(to='fume.Game'),
        ),
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Game'),
        ),
        migrations.AddField(
            model_name='reward',
            name='award_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Awarding'),
        ),
        migrations.AddField(
            model_name='reward',
            name='status',
            field=models.CharField(choices=[('act', 'Active'), ('exp', 'Expired'), ('use', 'Used')], default='act', max_length=3),
        ),
        migrations.AddField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='large_image',
            field=models.ImageField(upload_to=fume.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Publisher'),
        ),
        migrations.AlterField(
            model_name='game',
            name='small_image',
            field=models.ImageField(upload_to=fume.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(null=True, upload_to=fume.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='review',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Member'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Member'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Date of Purchase'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='games',
        ),
        migrations.AddField(
            model_name='transaction',
            name='games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Game'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Member'),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.AddField(
            model_name='membertag',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Member'),
        ),
        migrations.AddField(
            model_name='membertag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Tag'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Platform'),
        ),
    ]
