# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0003_auto_20170403_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='datetime',
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Purchase'),
        ),
    ]
