# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0004_auto_20170412_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='games',
            new_name='game',
        ),
    ]
