# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0005_auto_20170404_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='platform',
            new_name='platforms',
        ),
    ]
