# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0006_auto_20170413_0221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 11, 25, 33, 363770, tzinfo=utc), verbose_name='Date of Expiry'),
        ),
    ]
