# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0006_auto_20170404_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='recommended',
        ),
        migrations.AddField(
            model_name='member',
            name='purchased_games',
            field=models.ManyToManyField(null=True, to='fume.Game'),
        ),
    ]
