# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0007_auto_20170404_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='text',
        ),
    ]
