# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0007_auto_20170423_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 14, 45, 10, 778950, tzinfo=utc), verbose_name='Date of Expiry'),
        ),
    ]
