# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0008_auto_20170423_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 22, 16, 46, 20, 897679, tzinfo=utc), verbose_name='Date of Expiry'),
        ),
    ]
