# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0008_auto_20170404_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='award_datetime',
        ),
        migrations.AddField(
            model_name='reward',
            name='award_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Awarding'),
        ),
        migrations.AddField(
            model_name='reward',
            name='expiry_datetime',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Expiry'),
        ),
    ]
