# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0009_auto_20170404_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='purchased_games',
            field=models.ManyToManyField(blank=True, null=True, to='fume.Game'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Transaction'),
        ),
    ]
