# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0010_auto_20170404_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='body',
        ),
    ]
