# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0010_auto_20170425_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 25, 1, 30, 15, 897814, tzinfo=utc), verbose_name='Date of Expiry'),
        ),
    ]
