# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0011_auto_20170427_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 25, 15, 17, 4, 592013, tzinfo=utc), verbose_name='Date of Expiry'),
        ),
    ]
