# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0011_auto_20170404_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='count',
        ),
    ]
