# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0012_remove_tag_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='platforms',
            new_name='platform',
        ),
        migrations.RemoveField(
            model_name='member',
            name='purchased_games',
        ),
        migrations.AddField(
            model_name='game',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membertag',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fume.Game'),
        ),
    ]
