# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0012_auto_20170427_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 27, 12, 47, 53, 345200, tzinfo=utc), verbose_name='Date of Expiry'),
        ),
    ]
