# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0013_auto_20170429_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 27, 14, 20, 56, 939555, tzinfo=utc), verbose_name='Date of Expiry'),
        ),
    ]
