# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0013_auto_20170405_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='expiry_datetime',
            new_name='expiry_date',
        ),
    ]
