# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0014_auto_20170429_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 27, 15, 34, 19, 384069, tzinfo=utc), verbose_name='Date of Expiry'),
        ),
    ]
