# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0015_auto_20170429_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 29, 19, 38, 13, 927525, tzinfo=utc), verbose_name='Date of Expiry'),
        ),
    ]
